/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Calculo.MetodoSimplex;
import javax.swing.JOptionPane;

/**
 *
 * @author Bruno
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        carregarPainelPrimario();
    }
    
    private void carregarPainelPrimario(){
        jRadioButtonMaxLucro.setSelected(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMaxMinLucro = new javax.swing.ButtonGroup();
        Root = new javax.swing.JPanel();
        jPanelPrimario = new javax.swing.JPanel();
        jTextFieldQtdProdutos = new javax.swing.JTextField();
        jTextFieldQtdRestricoes = new javax.swing.JTextField();
        jButtonIniciar = new javax.swing.JButton();
        jRadioButtonMaxLucro = new javax.swing.JRadioButton();
        jRadioButtonMinCusto = new javax.swing.JRadioButton();
        jLabelResultado = new javax.swing.JLabel();
        jLabelQtdProdutos = new javax.swing.JLabel();
        jLabelQtdRestricoes = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Método simplex automatizado");
        setMinimumSize(new java.awt.Dimension(379, 415));
        getContentPane().setLayout(null);

        Root.setLayout(new java.awt.CardLayout());

        jPanelPrimario.setBackground(new java.awt.Color(204, 255, 255));
        jPanelPrimario.setMinimumSize(new java.awt.Dimension(379, 415));
        jPanelPrimario.setLayout(null);
        jPanelPrimario.add(jTextFieldQtdProdutos);
        jTextFieldQtdProdutos.setBounds(100, 60, 50, 30);
        jPanelPrimario.add(jTextFieldQtdRestricoes);
        jTextFieldQtdRestricoes.setBounds(250, 60, 59, 30);

        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });
        jPanelPrimario.add(jButtonIniciar);
        jButtonIniciar.setBounds(140, 110, 70, 30);

        buttonGroupMaxMinLucro.add(jRadioButtonMaxLucro);
        jRadioButtonMaxLucro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonMaxLucro.setText("Maximizar lucro");
        jRadioButtonMaxLucro.setContentAreaFilled(false);
        jPanelPrimario.add(jRadioButtonMaxLucro);
        jRadioButtonMaxLucro.setBounds(60, 20, 130, 25);

        buttonGroupMaxMinLucro.add(jRadioButtonMinCusto);
        jRadioButtonMinCusto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonMinCusto.setText("Minimizar custos");
        jRadioButtonMinCusto.setContentAreaFilled(false);
        jPanelPrimario.add(jRadioButtonMinCusto);
        jRadioButtonMinCusto.setBounds(200, 20, 140, 25);

        jLabelResultado.setText("Resultado: ");
        jLabelResultado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelPrimario.add(jLabelResultado);
        jLabelResultado.setBounds(20, 180, 340, 220);

        jLabelQtdProdutos.setText("Qtd. Produtos:");
        jPanelPrimario.add(jLabelQtdProdutos);
        jLabelQtdProdutos.setBounds(20, 70, 80, 14);

        jLabelQtdRestricoes.setText("Qtd. Restrições: ");
        jPanelPrimario.add(jLabelQtdRestricoes);
        jLabelQtdRestricoes.setBounds(160, 70, 100, 14);
        jPanelPrimario.add(jLabelStatus);
        jLabelStatus.setBounds(250, 390, 120, 14);

        Root.add(jPanelPrimario, "card2");

        getContentPane().add(Root);
        Root.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        MetodoSimplex metodoSimplex = new MetodoSimplex();
        if(Integer.parseInt(jTextFieldQtdProdutos.getText())>0 && Integer.parseInt(jTextFieldQtdRestricoes.getText())>0){
            jLabelStatus.setText("Carregando...");
            if(jRadioButtonMaxLucro.isSelected()){  //Se for para maximizar lucro
                jLabelResultado.setText(metodoSimplex.aplicarMetodoSimplex(Integer.parseInt(jTextFieldQtdProdutos.getText()),Integer.parseInt(jTextFieldQtdRestricoes.getText()),1)); //Aplica o metodo simplex, pedindo dados ao usuário e efetuando os cálculos.
            } else if (jRadioButtonMinCusto.isSelected()){
                JOptionPane.showMessageDialog(this, "Opção não disponível nessa versão.","Função indisponível",JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Marque se quer maximizar ou minimizar o lucro.", "Marque uma opção", JOptionPane.INFORMATION_MESSAGE);
            }
            jLabelStatus.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Digite valores positivos em quantidade de produtos e quantidade de restrições.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Root;
    private javax.swing.ButtonGroup buttonGroupMaxMinLucro;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JLabel jLabelQtdProdutos;
    private javax.swing.JLabel jLabelQtdRestricoes;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanelPrimario;
    private javax.swing.JRadioButton jRadioButtonMaxLucro;
    private javax.swing.JRadioButton jRadioButtonMinCusto;
    private javax.swing.JTextField jTextFieldQtdProdutos;
    private javax.swing.JTextField jTextFieldQtdRestricoes;
    // End of variables declaration//GEN-END:variables
}
